# Site settings
title: INTEGRAS
email: integrasplataforma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somos uma plataforma com o objetivo de auxiliar na elevação da qualidade de vida e bem-estar do usuário, 
  reunindo profissionais qualificados, conteúdo dinâmico e aplicável ao dia-a-dia, voltado para o seu bem estar.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "https://cscorsolino.github.io/integras/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: integrasplataforma
instagram_username:  integrasplataforma

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"